name: Update Resume Gist

on: 
  push:
    paths:
      - 'resume.json'

jobs:
  update-resume-gist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Update Gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        gist_id: c9dcfa1b37dec07fb2ee7f36d7278105
        file_path: resume.json
        file_name: resume.json
        description: "Yehualashet Feleke's Updated Resume"